#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [presentation]
#+BEAMER_FRAME_LEVEL: 1

#+BEAMER_HEADER_EXTRA: \usetheme{Warsaw}\usecolortheme{default}\useoutertheme{infolines}\setbeamercovered{transparent}
#+COLUMNS: %45ITEM %10BEAMER_env(Env) %10BEAMER_envargs(Env Args) %4BEAMER_col(Col) %8BEAMER_extra(Extra)
#+PROPERTY: BEAMER_col_ALL 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0 :ETC

#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [presentation]

#+LaTeX_HEADER: \usepackage[english]{babel} \usepackage{ae,aecompl}
#+LaTeX_HEADER: \usepackage{mathpazo,courier,euler} \usepackage[scaled=.95]{helvet}

#+LaTeX_HEADER: \usepackage{listings}

#+LaTeX_HEADER:\lstset{language=Python, basicstyle=\ttfamily\bfseries,
#+LaTeX_HEADER:  commentstyle=\color{red}\itshape, stringstyle=\color{darkgreen},
#+LaTeX_HEADER:  showstringspaces=false, keywordstyle=\color{blue}\bfseries}

#+TITLE:   
#+AUTHOR:    FOSSEE
#+EMAIL:     
#+DATE:    

#+DESCRIPTION: 
#+KEYWORDS: 
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:nil pri:nil tags:not-in-toc

* 
#+begin_latex
\begin{center}
\vspace{12pt}
\textcolor{blue}{\huge Conditionals}
\end{center}
\vspace{18pt}
\begin{center}
\vspace{10pt}
\includegraphics[scale=0.95]{../images/fossee-logo.png}\\
\vspace{5pt}
\scriptsize Developed by FOSSEE Team, IIT-Bombay. \\ 
\scriptsize Funded by National Mission on Education through ICT\\
\scriptsize  MHRD,Govt. of India\\
\includegraphics[scale=0.30]{../images/iitb-logo.png}\\
\end{center}
#+end_latex
* Objectives
At the end of this tutorial, you will be able to, 

 - Use if/else blocks. 
 - Use if/elif/else blocks.
 - Use the Ternary conditional statement - C if X else Y.
  
* Pre-requisite
Spoken tutorial on -
- Basic Datatypes and Operators
*  ~if/elif~ ladder
  #+begin_src python
    if user == 'admin':
        # Do admin operations
    elif user == 'moderator':
        # Do moderator operations
    elif user == 'client':
        # Do customer operations
  #+end_src
* Exercise 1
  Given a number, num. Write an if else block to print num, as is, if
  it is divisible by 10, else print 10 * num.
* Solution 1
  #+begin_src python
    if num%10 == 0: 
        print num   
    else:           
        print 10*num
  #+end_src

* Exercise 2
  Given a number, num. Write a ternary operator to print num, as is,
  if it is divisible by 10, else print 10 * num.
* Solution 2
  #+begin_src python
    print num if num%10 == 0 else 10*num
  #+end_src
* Pass statement
  #+begin_src python
    a = raw_input("Enter 'c' to calculate and exit, 'd' to display the existing
    results exit and 'x' to exit and any other key to continue: ")

    if a == 'c':
       # Calculate the marks and exit
    elif a == 'd':
       # Display the results and exit
    elif a == 'x':
       # Exit the program
    else:
       pass
  #+end_src
* Summary
 In this tutorial, we have learnt to,

  - Understand the conditional statements in Python.
  - Use if/else statement.
  - Use if/elif/else statement.
  - Apply the ternary conditional statement - C if X else Y.
  - Use "pass" statement.

* Evaluation
1. Use conditional statements for the following.
   Given a variable ``time``, print ``Good Morning`` if it is less
   than 12, otherwise ``Hello``. 

2. Convert the if else ladder below into a ternary conditional
   statement.
#+begin_src python
    x = 20

    if x > 10:
        print x * 100
    else:
        print x   
#+end_src

* Solutions
1. 
#+begin_src python
    if time < 12:
        print "Good Morning"
    else:
        print "Hello"
#+end_src

2.
#+begin_src python
 print x * 100 if x > 10 else x
#+end_src
* 
#+begin_latex
  \begin{block}{}
  \begin{center}
  \textcolor{blue}{\Large THANK YOU!} 
  \end{center}
  \end{block}
\begin{block}{}
  \begin{center}
    For more Information, visit our website\\
    \url{http://fossee.in/}
  \end{center}  
  \end{block}
\end{frame}
#+end_latex

